version: '3.8'

services:
  selenoid_cm:
    image: aerokube/cm
    volumes:
      - $PWD/selenoid/conf:/etc/selenoid
      - /var/run/docker.sock:/var/run/docker.sock
    command: |
      selenoid configure
      --config-dir /etc/selenoid
      --last-versions 1
      --browsers "chrome"
      --force
      --tmpfs 128

  selenoid:
    image: simple1elf/selenoid
    depends_on:
      - selenoid_cm
    restart: always
    network_mode: bridge
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/selenoid/video
    volumes:
      - $PWD/selenoid/conf:/etc/selenoid/
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/selenoid/video:/opt/selenoid/video
      - $PWD/selenoid/logs:/opt/selenoid/logs
    ports:
      - 4445:4444
    env_file:
      - .env
    command: |
      -limit 30
      -timeout 2m
      -service-startup-timeout 2m
      -session-attempt-timeout 2m
      -session-delete-timeout 2m
      -log-output-dir /opt/selenoid/logs
      -video-output-dir /opt/selenoid/video
      -s3-bucket-name selenoid
      -s3-endpoint https://storage.yandexcloud.net
      -s3-region ru-central1