version: '3.8'

services:
  selenoid_cm:
    image: aerokube/cm
    volumes:
      - $PWD/selenoid/conf:/etc/selenoid
      - /var/run/docker.sock:/var/run/docker.sock
    command: |
      selenoid configure
      --config-dir /etc/selenoid
      --last-versions 1
      --browsers "chrome"
      --force
      --tmpfs 128

  selenoid:
    image: aerokube/selenoid
    depends_on:
      - selenoid_cm
    restart: always
    network_mode: bridge
    volumes:
      - $PWD/selenoid/conf:/etc/selenoid/
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 4445:4444
    command: |
      -limit 20 -session-delete-timeout 60s
      -s3-endpoint https://storage.yandexcloud.net
      -s3-bucket-name selenoid
      -s3-region ru-central1
      -s3-access-key 6fokW2qVowYKmWhSQ-as
      -s3-secret-key WYpzLcoiJ1E6Fmk2fTHDv-fHU7JybD9KB2hdBnz8


  #      -s3-key-pattern $date/$sessionId.$fileExtension


  selenoid-ui:
    image: aerokube/selenoid-ui
    depends_on:
      - selenoid_cm
    restart: always
    network_mode: bridge
    links:
      - selenoid
    ports:
      - 8081:8080
    command: --selenoid-uri http://selenoid:4445